poll_manager/poll_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from polls.views import (index, add_poll, add_choice, view_single_poll, add_vote)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    # url(r'^$', test.polls.views.index', name='index'),
    url(r'add_poll/$', add_poll, name="add_poll"),
    url(r'^polls/(?P<poll_id>\d+)/add_choices/$', add_choice, name="add_choice"),
    url(r'^polls/$', view_polls, name="view_polls"),
    url(r'^polls/(?P<poll_id>\d+)/$', view_single_poll, name="detail_poll"),
    url(r'^polls/(?P<poll_id>\d+)/vote/$', add_vote, name="vote"),
]

poll_manager/polls/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Poll(models.Model):
	question = models.CharField(max_length=255)
	date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.question


class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice = models.CharField(max_length=255, blank=True)


class Votes(models.Model):
	poll = models.ForeignKey(Poll)
	choiceVote = models.ForeignKey(Choice)


class PollForm(ModelForm):
	class Meta:
		model = Poll

class ChoiceForm(ModelForm):
	class Meta:
		model = Choice
		fields = ('choice',)

poll_manager/polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import Context, loader, RequestContext
from django.shortcuts import render
from models import Poll, Choice, Votes, PollForm, ChoiceForm

# Create your views here.
def index(request):
	return render_to_response('index.html', context_instance = RequestContext(request),)

def add_poll(request):
	# calls the PollForm we created and displays it on the page
	if request.method == 'POST':
		form = PollForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('../.')
	else:
		form = PollForm()
	return render_to_response('add_poll.html', {'form': form}, context_instance = RequestContext(request),)


def add_choice(request, poll_id):
	poll = Poll.objects.get(id=poll_id)
	if request.method == 'POST':
		form = ChoiceForm(request.POST)
		if form.is_valid():
			#uses false commit to save the poll as the current poll ID, sets initial vote to 0, and saves all choices the user
			#has put in the form
			add_poll = form.save(commit=False)
			add_poll.poll = poll
			add_poll.vote = 0
			add_poll.save()
			form.save()
		return HttpResponseRedirect('../.')
		else:
			form = ChoiceForm()
		return render_to_response('add_choices.html', {'form': form, 'poll_id': poll_id,}, context_instance=RequestContext(request,),)


def view_polls(request):
	poll_query = Poll.objects.all().order_by('date')
	return render_to_response('polls.html', {'poll_query': poll_query, })


def view_single_poll(request, poll_id):
	poll = Poll.objects.get(id=poll_id)
	choices = poll.choice_set.all().order_by('id')
	return render_to_response('poll_info.html', {'poll': poll, 'choices': choices,}, context_instance=RequestContext(request,),)


def add_vote(request, poll_id):
	poll = Poll.objects.get(id=poll_id)
	choice = Choice.objects.filter(poll=poll_id).order_by('id')
	if request.method == 'POST':
		vote = request.POST.get('choice')
		if vote:
			vote = Choice.objects.get(id=vote)
			# saves the poll id, user id, and choice to the votes table
			v = Votes(poll=poll, choiceVote = vote)
			v.save()
			# redirects the user to the results page after they submit their vote
			return HttpResponseRedirect('../.')
		return render_to_response('votes.html', {'choice': choice, 'poll': poll, 'vcount': vcount,}, context_instance=RequestContext(request))

def view_results(request, poll_id):
	# display the choices and number of votes they have - displaying the number of votes is done in the  view_results template
	poll = Poll.objects.get(id=poll_id)
	choices = poll.choice_set.all()
	return render_to_response('poll_info.html', vars())

poll_manager/polls/templates/add_choices.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Add a Poll</title>
</head>>
<body>
    <p>Add Choices</p>
    <form id="choice" name="" action="" method="post"> {% csrf_token %}
    	<fieldset>
		<label for="id_choice">Choice: </label> {{ form.choice }}
		<input id="submit" type="submit" value="Submit" />
	</fieldset>
    </form>

</body>
</html>

poll_manager/polls/templates/add_poll.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Add a Poll</title>
</head>
<body>

    <p>Add a Poll</p>
    <form name="addPoll" action="/add_choices/" method="post"> {% csrf_toke %}
	<fieldset>
		<label id="questionID" for="id_question">Question: </label> {{ form.question }}
		<input id="submit" type="submit" value="Submit" />
	</fieldset>
    </form>
</body>
</html>

poll_manager/polls/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Poll Manager Home</title>
</head>

<body>
	<p>Welcome!</p>
	<p><a href="{% url polls %}"> View Polls</a></p>
	<p><a href="{% url add_poll %}"> Add a poll</a></p>
</body>

</html>

poll_manager/polls/templates/poll_info.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Add a Poll</title>
</head>
<body>
    <p><a href="add_choices/">Add choices</a></p>
    <p><a href="vote/">Click here to vote</a></p>

	{% for choice in choices %}
		<p class="resultsList"> {{ choice.choice }} - {{ choice.votes_set.count }} </p>
	{% endfor %}

</body>
</hmtl>

poll_manager/polls/templates/polls.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Vote!</title>
</head>
<body>
    <p>Here's a list of polls</p>
    {% if poll_query %}
	<ul>
		{% for poll in poll_query %}
			<li><a href="{{ poll.id }}/"> {{ poll.question }} </a></li>
		{% endfor %}
	</ul>

	{% else %}
		<p> there are no polls available</p>

	{% endif %}

</body>
</html>

poll_manager/polls/templates/votes.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Vote!</title>
</head>
<body>
	<p> {{ poll.question }}</p>
	{% if choice %}
	<form method="post" action="" id="voteForm"> {% csrf_toke %}
		<fieldset>
			{% for choice in choice %}
				<p><input type="radio" name="choice" id="choice" value="{{ choice.id }}" />
				<label for="choice{{ forloop.counter > {{ choice.choice }} </label></p>
			{% endfor %}
			
			<input type="submit" id="submit" value="Submit" />
		</fieldset>
	</form>
	{% else %}
	<p class="noChoice"> No votes have been added to this poll yet!</p>
	{% endif %}

</body>
</html>